src/lib/components/custom/tab-bar/tab-bar.svelte, src/lib/components/custom/tab-bar/tab-content.svelte, src/lib/components/custom/tab-bar/tab-store.svelte.ts, src/routes/csstest/+page.svelte
Generic tab bar component, implemented similarly how the `Select` component is implemented. It depends on the `Button` component for now.
Can be tested at `/csstest`
Closes #35
=> feat: tab bar component

svelte.config.js
=> fix: prettify generated code

src/lib/components/ui/select/select.svelte
resolve #53
resolve #54 
resolve #52
=> fix: select:focus border color,select menu cover input,width of options

package.json, pnpm-lock.yaml, src/lib/components/ui/select/select.svelte
=> fix(select): bindable value, onchange and oninput events

src/lib/components/ui/button.svelte
=> fix: added rules so the button doesn't float vertically

src/lib/components/ui/select/option.svelte, src/lib/components/ui/select/select-store.svelte.ts, src/lib/components/ui/select/select.svelte
=> fix: navigation don't change the value in Select

src/lib/components/ui/button.svelte, src/lib/components/ui/checkbox.svelte, src/lib/components/ui/input.svelte, src/lib/components/ui/menu/menu-title.svelte, src/lib/components/ui/radio.svelte, src/lib/components/ui/select/option.svelte, src/lib/components/ui/select/select.svelte, src/lib/components/ui/switch.svelte, src/lib/components/ui/typography.svelte
=> chore: remove unnecessary type definition

src/lib/components/ui/select/select.svelte
=> fix: opening and closing the menu by clicking the caret

src/lib/components/ui/select/select.svelte, src/routes/+page.svelte
=> feat: use helper text snippet instead of helper text string

src/lib/components/ui/button.svelte
=> fix: button doesn't use all horizontal space

src/lib/components/ui/select/select.svelte
=> fix: select text color

src/lib/components/ui/select/select.svelte, src/routes/components/button/+page.svelte
Adds helper texts to inputs, fixes helper text alignment, adds missing sections.
=> fix: button component page missing elements

src/lib/components/custom/component-template.svelte, src/routes/+layout.svelte, src/routes/components/button/+page.svelte
Also updated the colors according to the design in Figma.
Fixes #99
=> fix: highlight selected menuitem

src/lib/components/ui/radio.svelte
=> fix: radio button clickable area

src/app.pcss, src/lib/components/custom/code.svelte, src/lib/components/custom/highlight-diete.css, src/lib/utils/colors.ts
=> fix: code background color

src/lib/components/ui/button.svelte, src/lib/utils/colors.ts
This merges to #89 so that needs to be merged first!
Fixes #88
=> fix: dark overlay button colors

src/lib/components/custom/dropdown.svelte, src/routes/+layout.svelte
Also replaces slots with snippets.
Fixes #92
=> fix: dropdown button stays pressed

src/routes/+layout.svelte
This PR makes sure that the menu title is open if the active page is in the menu. Also changed the menu generation to loop through a predefined menu structure.
=> feat: active menu tracking

src/app.pcss, src/lib/components/ui/button.svelte, src/lib/utils/colors.ts, src/routes/+page.svelte, src/routes/components/button/+page.svelte
Added light overlay button variant along with light color calculations. Also fixed the dark overlay transparency. Removed all the unnecessary borders from buttons.
=> feat: light overlay button

src/lib/components/ui/select/select.svelte
=> fix: select uses all horizontal empty  space

src/lib/components/ui/select/select.svelte
=> fix: select bound value

src/lib/components/ui/select/select.svelte
=> fix: added border-radius to div.options

src/lib/components/ui/slider.svelte
resolve #145 
resolve partially #146
=> fix: circle should be base background when focused input

src/lib/components/ui/slider.svelte, src/routes/+page.svelte
=> feat: slider steps without snapping

src/lib/components/ui/slider.svelte
=> fix: slider helperText at horizontal layout

src/lib/components/ui/menu/menu-title.svelte
=> fix: menu clickable area

src/lib/components/custom/theme-selector.svelte, src/lib/utils/colors.ts
=> feat: input validation color

src/lib/components/custom/highlight-diete.css
=> fix: code font and size

src/routes/+layout.svelte
=> feat: page title

src/lib/components/ui/checkbox.svelte
=> fix: added variable instead of hard coded

src/app.pcss
=> fix: checkbox size

src/lib/components/ui/slider.svelte
=> fix: slider step position

src/lib/components/ui/radio-button/radio.svelte
=> fix: selected radio has high color

src/routes/+layout.svelte, src/routes/components/typography/+page.svelte
=> feat: typography component page

src/lib/components/ui/radio-button/radio-group.svelte, src/routes/+page.svelte
=> fix: radio group gap at landing page

src/lib/components/custom/component-template.svelte, src/lib/components/ui/input.svelte, src/lib/components/ui/select/select.svelte, src/routes/+page.svelte
=> fix: input and select fill available space automatically

src/lib/components/ui/input.svelte, src/routes/components/input/+page.svelte, src/routes/test/+page.svelte
=> feat: solid variant at input

src/lib/components/ui/badge.svelte, src/routes/+layout.svelte, src/routes/components/badge/+page.svelte, src/routes/test/+page.svelte
=> feat: badge component

src/lib/components/ui/select/select.svelte, src/routes/components/select/+page.svelte, src/routes/test/+page.svelte
=> feat: select solid variant

src/lib/components/custom/component-template.svelte
Check out the select or input component pages.
=> fix: component template preview padding

src/lib/components/ui/menu/menu-title.svelte, src/routes/+layout.svelte, src/routes/components/menu/+page.svelte, src/routes/test/+page.svelte
=> fix: use Snippet instead of string at menu-title component

src/lib/components/ui/menu/menu-title.svelte
=> fix: menu opens by pressing enter

src/routes/components/input/+page.svelte
=> feat: added Button component source code to the Input page

src/lib/stores/theme.svelte.ts
=> feat: stored the theme and load at start

src/lib/components/ui/progress.svelte, src/routes/components/progress/+page.svelte
=> feat: extended progress bar by unit and min,max

src/lib/components/custom/component-template.svelte, src/lib/components/ui/input.svelte, src/lib/components/ui/select/select.svelte, src/routes/+page.svelte
=> fix: select and input fill all available space

src/lib/components/ui/slider.svelte, src/routes/components/slider/+page.svelte
=> feat: slider with actual value on the right

src/routes/+layout.svelte, src/routes/components/textarea/+page.svelte
=> feat: textarea component page

src/lib/components/ui/input.svelte, src/routes/+page.svelte
=> fix: layout at intro page

src/diete.css, src/lib/components/ui/badge.svelte, src/lib/components/ui/button.svelte, src/lib/components/ui/checkbox.svelte, src/lib/components/ui/input.svelte, src/lib/components/ui/menu/menu-title.svelte, src/lib/components/ui/radio-button/radio.svelte, src/lib/components/ui/range-slider.svelte, src/lib/components/ui/select/option.svelte, src/lib/components/ui/select/select.svelte, src/lib/components/ui/slider.svelte, src/lib/components/ui/switch.svelte, src/lib/components/ui/textarea.svelte, src/lib/components/ui/tooltip.svelte
=> fix: paddings of components use variables

src/routes/+page.svelte
=> fix: section call-to-action can be wrapped

src/lib/components/custom/code.svelte
=> fix: Code component breaks line

src/lib/components/ui/textarea.svelte
=> fix: textarea min-height

src/lib/components/ui/button.svelte, src/lib/components/ui/checkbox.svelte, src/lib/components/ui/input/input.svelte, src/lib/components/ui/menu/menu-title.svelte, src/lib/components/ui/radio-button/radio-group.svelte, src/lib/components/ui/radio-button/radio.svelte, src/lib/components/ui/range-slider.svelte, src/lib/components/ui/select/option.svelte, src/lib/components/ui/select/select.svelte, src/lib/components/ui/slider.svelte, src/lib/components/ui/switch.svelte, src/lib/components/ui/textarea.svelte
=> fix: border-radius is variable instead of hard coded value

src/routes/+page.svelte
=> feat: build missing section of the homepage

src/routes/+page.svelte
=> fix: gap at main page in badge overlay section

src/diete.css, src/lib/components/ui/button.svelte, src/lib/components/ui/checkbox.svelte, src/lib/components/ui/input/input.svelte, src/lib/components/ui/menu/menu-title.svelte, src/lib/components/ui/radio-button/radio-group.svelte, src/lib/components/ui/radio-button/radio.svelte, src/lib/components/ui/range-slider.svelte, src/lib/components/ui/select/select.svelte, src/lib/components/ui/slider.svelte, src/lib/components/ui/switch.svelte, src/lib/components/ui/textarea.svelte
=> feat: outline variable

src/lib/components/ui/loader.svelte, src/routes/test/+page.svelte
=> feat: overwritten colors in the loader

src/lib/components/ui/input/color-input.svelte, src/lib/components/ui/input/search-input.svelte
=> fix: border color at search and color solid input

src/lib/components/ui/input/date-input.svelte, src/lib/components/ui/input/input.svelte, src/routes/test/+page.svelte
=> feat: date picker 

src/lib/components/ui/textarea.svelte
=> fix: textarea max-width

src/lib/components/ui/progress.svelte
=> feat: showValue prop on Progress component

src/lib/components/ui/menu/menu-title.svelte, src/lib/components/ui/select/option.svelte, src/lib/components/ui/select/select.svelte
=> feat: icon size change automatically based on dimension

src/lib/components/ui/checkbox.svelte
=> fix: checkbox visual bug on iOS

src/lib/components/ui/input/date-input.svelte
=> fix: date input class attribute is applied to calendar-root

src/lib/components/ui/input/date-input.svelte
=> fix: date input focus after click on icon

src/lib/components/ui/input/date-input.svelte
=> fix: menu button and theme button in date input  isnt need to rewrite
